import type { BodyPart, Exercise, TargetArea } from "./types";

/**
 * 種目ライブラリ。
 *
 * video は現時点ではすべて null。naru本人のお手本動画を撮影したら
 * public/videos/{id}.mp4 と public/videos/{id}.jpg を置いて
 * video: { src: "/videos/{id}.mp4", poster: "/videos/{id}.jpg" } に差し替えるだけで
 * 実行画面・種目詳細に自動で反映されます。
 */
export const EXERCISES: Exercise[] = [
  // ───────────── ウォームアップ ─────────────
  {
    id: "arm-circles",
    name: "アームサークル",
    nameEn: "Arm Circles",
    parts: ["shoulders"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "warmup",
    seconds: 30,
    met: 2.8,
    cues: ["肩の力を抜いて、腕は大きくゆっくり回す", "肩甲骨から動かすイメージ"],
    mistakes: ["首をすくめて回してしまう", "スピードだけ速くなる"],
    breathing: "自然な呼吸のまま。止めない",
    video: null,
  },
  {
    id: "cat-cow",
    name: "キャット＆カウ",
    nameEn: "Cat and Cow",
    parts: ["back", "abs"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "warmup",
    seconds: 40,
    met: 2.5,
    cues: ["手は肩の真下、膝は股関節の真下", "背骨を1本ずつ動かすようにゆっくり"],
    mistakes: ["腰だけで反ってしまう", "動きが速すぎる"],
    breathing: "反るときに吸う、丸めるときに吐く",
    video: null,
  },
  {
    id: "hip-circles",
    name: "ヒップサークル",
    nameEn: "Hip Circles",
    parts: ["glutes", "legs"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "warmup",
    seconds: 30,
    met: 2.5,
    cues: ["足は肩幅、手は腰に添える", "股関節から大きく円を描く"],
    mistakes: ["膝だけが動いている", "上半身が一緒に振られる"],
    breathing: "自然な呼吸",
    video: null,
  },
  {
    id: "march-in-place",
    name: "その場マーチ",
    nameEn: "March in Place",
    parts: ["cardio", "legs"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "warmup",
    seconds: 40,
    met: 3.5,
    cues: ["ももを腰の高さまで上げる", "腕も一緒に大きく振る"],
    mistakes: ["前かがみになる", "足音が大きい（着地が強い）"],
    breathing: "リズムよく吸って吐く",
    video: null,
  },

  // ───────────── 腹筋 ─────────────
  {
    id: "crunch",
    name: "クランチ",
    nameEn: "Crunch",
    parts: ["abs"],
    equipment: ["none"],
    difficulty: 1,
    measure: "reps",
    phase: "main",
    reps: 15,
    seconds: 40,
    met: 3.8,
    cues: ["おへそを覗き込むように背中を丸める", "肩甲骨が床から離れるところまででOK"],
    mistakes: ["手で首を引っ張る", "反動で起き上がる"],
    breathing: "起き上がるときに吐く、戻すときに吸う",
    video: null,
  },
  {
    id: "plank",
    name: "プランク",
    nameEn: "Plank",
    parts: ["abs"],
    equipment: ["none"],
    difficulty: 2,
    measure: "time",
    phase: "main",
    seconds: 40,
    met: 3.5,
    cues: ["肘は肩の真下", "頭からかかとまで一直線", "お尻を締めて骨盤を立てる"],
    mistakes: ["腰が落ちる", "お尻が高く上がる", "呼吸を止める"],
    breathing: "止めずに細く長く吐き続ける",
    video: null,
  },
  {
    id: "leg-raise",
    name: "レッグレイズ",
    nameEn: "Leg Raise",
    parts: ["abs"],
    equipment: ["none"],
    difficulty: 2,
    measure: "reps",
    phase: "main",
    reps: 12,
    seconds: 40,
    met: 4.0,
    cues: ["腰を床に押しつけたまま脚を下ろす", "下ろすときこそゆっくり"],
    mistakes: ["腰が浮いて反る", "下ろす動作が速すぎる"],
    breathing: "下ろすときに吸う、上げるときに吐く",
    video: null,
  },
  {
    id: "bicycle-crunch",
    name: "バイシクルクランチ",
    nameEn: "Bicycle Crunch",
    parts: ["abs"],
    equipment: ["none"],
    difficulty: 2,
    measure: "time",
    phase: "main",
    seconds: 40,
    met: 5.0,
    unilateral: true,
    cues: ["肘と膝ではなく“肩と骨盤”を近づける", "伸ばす脚は床すれすれ"],
    mistakes: ["首に力が入る", "速く回しすぎて効いていない"],
    breathing: "ひねるたびに短く吐く",
    video: null,
  },
  {
    id: "russian-twist",
    name: "ロシアンツイスト",
    nameEn: "Russian Twist",
    parts: ["abs"],
    equipment: ["none"],
    difficulty: 2,
    measure: "time",
    phase: "main",
    seconds: 40,
    met: 4.0,
    cues: ["胸を張ったまま、みぞおちから回す", "目線も手と一緒に動かす"],
    mistakes: ["背中が丸まる", "腕だけ振っている"],
    breathing: "ひねりきったところで吐く",
    video: null,
  },
  {
    id: "dead-bug",
    name: "デッドバグ",
    nameEn: "Dead Bug",
    parts: ["abs"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "main",
    seconds: 40,
    met: 3.5,
    unilateral: true,
    cues: ["腰と床のすき間をゼロに保つ", "対角の手足をゆっくり伸ばす"],
    mistakes: ["腰が浮く", "動きが速い"],
    breathing: "伸ばすときに吐く",
    video: null,
  },
  {
    id: "side-plank",
    name: "サイドプランク",
    nameEn: "Side Plank",
    parts: ["abs"],
    equipment: ["none"],
    difficulty: 2,
    measure: "time",
    phase: "main",
    seconds: 30,
    met: 3.5,
    unilateral: true,
    cues: ["肘は肩の真下", "腰を高く押し上げて一直線"],
    mistakes: ["腰が落ちる", "体が前後に傾く"],
    breathing: "細く長く吐き続ける",
    video: null,
  },
  {
    id: "heel-touch",
    name: "ヒールタッチ",
    nameEn: "Heel Touch",
    parts: ["abs"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "main",
    seconds: 40,
    met: 3.8,
    unilateral: true,
    cues: ["肩を少し浮かせたまま左右に体を倒す", "脇腹が縮む感覚を意識"],
    mistakes: ["肩が床についてしまう", "腕を伸ばすだけになる"],
    breathing: "倒すたびに吐く",
    video: null,
  },
  {
    id: "v-sit",
    name: "Vシット",
    nameEn: "V-Sit",
    parts: ["abs"],
    equipment: ["none"],
    difficulty: 3,
    measure: "reps",
    phase: "main",
    reps: 12,
    seconds: 40,
    met: 5.0,
    cues: ["上半身と脚を同時に持ち上げてVをつくる", "手は足先に向かって伸ばす"],
    mistakes: ["反動を使う", "背中が丸まりきって首が痛くなる"],
    breathing: "上げるときに吐く",
    video: null,
  },

  // ───────────── 胸 ─────────────
  {
    id: "knee-pushup",
    name: "膝つきプッシュアップ",
    nameEn: "Knee Push-Up",
    parts: ["chest", "arms"],
    equipment: ["none"],
    difficulty: 1,
    measure: "reps",
    phase: "main",
    reps: 10,
    seconds: 40,
    met: 3.8,
    cues: ["手は肩幅よりやや広く", "膝から頭まで一直線をキープ"],
    mistakes: ["お尻が突き出る", "肘が真横に開きすぎる"],
    breathing: "下ろすときに吸う、押すときに吐く",
    video: null,
  },
  {
    id: "pushup",
    name: "プッシュアップ",
    nameEn: "Push-Up",
    parts: ["chest", "arms", "abs"],
    equipment: ["none"],
    difficulty: 2,
    measure: "reps",
    phase: "main",
    reps: 12,
    seconds: 40,
    met: 4.5,
    cues: ["肘は45度に締める", "胸から下ろして胸から上げる"],
    mistakes: ["腰が落ちる", "可動域が浅い"],
    breathing: "下ろすときに吸う、押すときに吐く",
    video: null,
  },
  {
    id: "wide-pushup",
    name: "ワイドプッシュアップ",
    nameEn: "Wide Push-Up",
    parts: ["chest"],
    equipment: ["none"],
    difficulty: 2,
    measure: "reps",
    phase: "main",
    reps: 10,
    seconds: 40,
    met: 4.5,
    cues: ["手幅を肩幅の1.5倍に", "胸の外側が伸びるのを感じる"],
    mistakes: ["肩がすくむ", "手を広げすぎて肩を痛める"],
    breathing: "下ろすときに吸う、押すときに吐く",
    video: null,
  },
  {
    id: "incline-pushup",
    name: "インクラインプッシュアップ",
    nameEn: "Incline Push-Up",
    parts: ["chest", "arms"],
    equipment: ["chair"],
    difficulty: 1,
    measure: "reps",
    phase: "main",
    reps: 12,
    seconds: 40,
    met: 3.5,
    cues: ["椅子やテーブルに手をつく", "高さがあるほど楽になる"],
    mistakes: ["台がぐらつく場所を選ぶ", "腰が反る"],
    breathing: "下ろすときに吸う、押すときに吐く",
    video: null,
  },
  {
    id: "diamond-pushup",
    name: "ダイヤモンドプッシュアップ",
    nameEn: "Diamond Push-Up",
    parts: ["arms", "chest"],
    equipment: ["none"],
    difficulty: 3,
    measure: "reps",
    phase: "main",
    reps: 8,
    seconds: 40,
    met: 5.0,
    cues: ["親指と人差し指でひし形をつくる", "肘は体の横にしまう"],
    mistakes: ["肘が外に開く", "手首が痛いまま続ける"],
    breathing: "下ろすときに吸う、押すときに吐く",
    video: null,
  },

  // ───────────── 腕と背中・肩 ─────────────
  {
    id: "chair-dips",
    name: "チェアディップス",
    nameEn: "Chair Dips",
    parts: ["arms"],
    equipment: ["chair"],
    difficulty: 2,
    measure: "reps",
    phase: "main",
    reps: 12,
    seconds: 40,
    met: 4.5,
    cues: ["椅子の縁を掴み、お尻を前にずらす", "肘は後ろにまっすぐ曲げる"],
    mistakes: ["肩がすくむ", "お尻が椅子から離れすぎる"],
    breathing: "下ろすときに吸う、押すときに吐く",
    video: null,
  },
  {
    id: "superman",
    name: "スーパーマン",
    nameEn: "Superman",
    parts: ["back", "glutes"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "main",
    seconds: 30,
    met: 3.5,
    cues: ["うつ伏せで対角の手足を伸ばして持ち上げる", "首は長く、目線は床"],
    mistakes: ["首を反らして上を見る", "反動で上げる"],
    breathing: "上げるときに吐く",
    video: null,
  },
  {
    id: "reverse-plank",
    name: "リバースプランク",
    nameEn: "Reverse Plank",
    parts: ["back", "glutes", "abs"],
    equipment: ["none"],
    difficulty: 2,
    measure: "time",
    phase: "main",
    seconds: 30,
    met: 3.5,
    cues: ["手は肩の真下、胸を開く", "お尻を高く持ち上げて一直線"],
    mistakes: ["お尻が落ちる", "肩がすくむ"],
    breathing: "細く長く吐き続ける",
    video: null,
  },
  {
    id: "shoulder-tap",
    name: "ショルダータップ",
    nameEn: "Shoulder Tap",
    parts: ["shoulders", "abs"],
    equipment: ["none"],
    difficulty: 2,
    measure: "time",
    phase: "main",
    seconds: 40,
    met: 4.0,
    unilateral: true,
    cues: ["足を広めにして体を安定させる", "腰を左右に振らない"],
    mistakes: ["お尻が左右に揺れる", "手を出すのが速すぎる"],
    breathing: "タッチのたびに吐く",
    video: null,
  },
  {
    id: "pike-pushup",
    name: "パイクプッシュアップ",
    nameEn: "Pike Push-Up",
    parts: ["shoulders", "arms"],
    equipment: ["none"],
    difficulty: 3,
    measure: "reps",
    phase: "main",
    reps: 8,
    seconds: 40,
    met: 5.0,
    cues: ["お尻を高く上げて山をつくる", "頭を手の前方に下ろす"],
    mistakes: ["背中が丸まる", "肘が外に開く"],
    breathing: "下ろすときに吸う、押すときに吐く",
    video: null,
  },
  {
    id: "band-pull-apart",
    name: "バンドプルアパート",
    nameEn: "Band Pull Apart",
    parts: ["back", "shoulders"],
    equipment: ["band"],
    difficulty: 1,
    measure: "reps",
    phase: "main",
    reps: 15,
    seconds: 40,
    met: 3.5,
    cues: ["肩甲骨を寄せてバンドを横に引く", "肘は軽く伸ばしたまま"],
    mistakes: ["肩がすくむ", "腰が反る"],
    breathing: "引くときに吐く",
    video: null,
  },
  {
    id: "db-row",
    name: "ダンベルロウ",
    nameEn: "Dumbbell Row",
    parts: ["back", "arms"],
    equipment: ["dumbbell"],
    difficulty: 2,
    measure: "reps",
    phase: "main",
    reps: 12,
    seconds: 45,
    met: 5.0,
    unilateral: true,
    cues: ["背中は真っすぐ、股関節から前傾", "肘を腰に向かって引く"],
    mistakes: ["腕だけで引く", "体をひねって反動を使う"],
    breathing: "引くときに吐く",
    video: null,
  },
  {
    id: "db-curl",
    name: "ダンベルカール",
    nameEn: "Dumbbell Curl",
    parts: ["arms"],
    equipment: ["dumbbell"],
    difficulty: 1,
    measure: "reps",
    phase: "main",
    reps: 12,
    seconds: 40,
    met: 3.5,
    cues: ["肘の位置を体の横で固定", "下ろすときも力を抜かない"],
    mistakes: ["肘が前に出る", "反動で上げる"],
    breathing: "上げるときに吐く",
    video: null,
  },
  {
    id: "db-shoulder-press",
    name: "ダンベルショルダープレス",
    nameEn: "Dumbbell Shoulder Press",
    parts: ["shoulders", "arms"],
    equipment: ["dumbbell"],
    difficulty: 2,
    measure: "reps",
    phase: "main",
    reps: 12,
    seconds: 45,
    met: 5.0,
    cues: ["肋骨を締めて、真上に押し上げる", "耳の横を通す軌道"],
    mistakes: ["腰が反る", "肩がすくむ"],
    breathing: "押すときに吐く",
    video: null,
  },

  // ───────────── 脚とヒップ ─────────────
  {
    id: "squat",
    name: "スクワット",
    nameEn: "Squat",
    parts: ["legs", "glutes"],
    equipment: ["none"],
    difficulty: 1,
    measure: "reps",
    phase: "main",
    reps: 15,
    seconds: 45,
    met: 5.0,
    cues: ["足は肩幅、つま先はやや外", "お尻を後ろに引きながら下ろす", "膝とつま先の向きを揃える"],
    mistakes: ["膝が内側に入る", "かかとが浮く", "背中が丸まる"],
    breathing: "下ろすときに吸う、立つときに吐く",
    video: null,
  },
  {
    id: "wide-squat",
    name: "ワイドスクワット",
    nameEn: "Wide Squat",
    parts: ["legs", "glutes"],
    equipment: ["none"],
    difficulty: 1,
    measure: "reps",
    phase: "main",
    reps: 15,
    seconds: 45,
    met: 5.0,
    cues: ["足幅は肩幅の1.5倍、つま先は45度外", "内ももを意識して立ち上がる"],
    mistakes: ["膝が内に入る", "上体が前に倒れる"],
    breathing: "下ろすときに吸う、立つときに吐く",
    video: null,
  },
  {
    id: "lunge",
    name: "ランジ",
    nameEn: "Lunge",
    parts: ["legs", "glutes"],
    equipment: ["none"],
    difficulty: 2,
    measure: "reps",
    phase: "main",
    reps: 12,
    seconds: 45,
    met: 5.5,
    unilateral: true,
    cues: ["前の膝はつま先の真上まで", "上体は真っすぐ、真下に落とす"],
    mistakes: ["前の膝がつま先より前に出る", "上体が前に倒れる"],
    breathing: "下ろすときに吸う、戻すときに吐く",
    video: null,
  },
  {
    id: "bulgarian-squat",
    name: "ブルガリアンスクワット",
    nameEn: "Bulgarian Split Squat",
    parts: ["legs", "glutes"],
    equipment: ["chair"],
    difficulty: 3,
    measure: "reps",
    phase: "main",
    reps: 10,
    seconds: 45,
    met: 6.0,
    unilateral: true,
    cues: ["後ろ足を椅子に乗せる", "前足に体重の8割を乗せる"],
    mistakes: ["歩幅が狭くて膝が前に出る", "バランスを崩して体が傾く"],
    breathing: "下ろすときに吸う、立つときに吐く",
    video: null,
  },
  {
    id: "hip-thrust",
    name: "ヒップリフト",
    nameEn: "Glute Bridge",
    parts: ["glutes", "legs"],
    equipment: ["none"],
    difficulty: 1,
    measure: "reps",
    phase: "main",
    reps: 15,
    seconds: 40,
    met: 4.0,
    cues: ["かかとで床を押す", "一番上でお尻を1秒締める"],
    mistakes: ["腰で反り上げる", "膝が開く"],
    breathing: "上げるときに吐く",
    video: null,
  },
  {
    id: "single-leg-bridge",
    name: "シングルレッグヒップリフト",
    nameEn: "Single Leg Glute Bridge",
    parts: ["glutes"],
    equipment: ["none"],
    difficulty: 2,
    measure: "reps",
    phase: "main",
    reps: 10,
    seconds: 40,
    met: 4.5,
    unilateral: true,
    cues: ["片脚を伸ばして骨盤を水平に保つ", "支え脚のかかとで押す"],
    mistakes: ["骨盤が左右に傾く", "腰で上げる"],
    breathing: "上げるときに吐く",
    video: null,
  },
  {
    id: "donkey-kick",
    name: "ドンキーキック",
    nameEn: "Donkey Kick",
    parts: ["glutes"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "main",
    seconds: 30,
    met: 4.0,
    unilateral: true,
    cues: ["四つ這いで膝を90度に曲げたまま天井へ", "お尻の力だけで上げる"],
    mistakes: ["腰を反って上げる", "体が横に開く"],
    breathing: "上げるときに吐く",
    video: null,
  },
  {
    id: "side-leg-raise",
    name: "サイドレッグレイズ",
    nameEn: "Side Leg Raise",
    parts: ["glutes", "legs"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "main",
    seconds: 30,
    met: 3.5,
    unilateral: true,
    cues: ["横向きで体を一直線に", "つま先は正面のまま上げる"],
    mistakes: ["体が後ろに倒れる", "つま先が天井を向く"],
    breathing: "上げるときに吐く",
    video: null,
  },
  {
    id: "calf-raise",
    name: "カーフレイズ",
    nameEn: "Calf Raise",
    parts: ["legs"],
    equipment: ["none"],
    difficulty: 1,
    measure: "reps",
    phase: "main",
    reps: 20,
    seconds: 40,
    met: 3.5,
    cues: ["かかとを限界まで上げて1秒止める", "下ろすときはゆっくり"],
    mistakes: ["反動で弾む", "可動域が浅い"],
    breathing: "上げるときに吐く",
    video: null,
  },
  {
    id: "wall-sit",
    name: "ウォールシット",
    nameEn: "Wall Sit",
    parts: ["legs"],
    equipment: ["none"],
    difficulty: 2,
    measure: "time",
    phase: "main",
    seconds: 40,
    met: 4.5,
    cues: ["壁に背中をぴったりつけて膝90度", "太ももの前が焼ける感覚をキープ"],
    mistakes: ["膝がつま先より前に出る", "腰が壁から離れる"],
    breathing: "止めずに細く吐き続ける",
    video: null,
  },
  {
    id: "squat-jump",
    name: "スクワットジャンプ",
    nameEn: "Squat Jump",
    parts: ["legs", "cardio", "glutes"],
    equipment: ["none"],
    difficulty: 3,
    measure: "time",
    phase: "main",
    seconds: 30,
    met: 8.0,
    cues: ["着地は音を立てずやわらかく", "着地したらそのまましゃがんで次へつなげる"],
    mistakes: ["膝が内に入る", "着地が硬い"],
    breathing: "跳ぶときに吐く",
    video: null,
  },

  // ───────────── 有酸素 ─────────────
  {
    id: "jumping-jack",
    name: "ジャンピングジャック",
    nameEn: "Jumping Jack",
    parts: ["cardio", "fullbody"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "main",
    seconds: 40,
    met: 8.0,
    cues: ["手足を同時に大きく開く", "膝を軽く曲げて着地"],
    mistakes: ["腕が上がりきらない", "着地が硬い"],
    breathing: "リズムよく吸って吐く",
    video: null,
  },
  {
    id: "high-knees",
    name: "ハイニー",
    nameEn: "High Knees",
    parts: ["cardio", "abs", "legs"],
    equipment: ["none"],
    difficulty: 2,
    measure: "time",
    phase: "main",
    seconds: 30,
    met: 8.0,
    cues: ["ももを腰の高さまで", "つま先着地でリズムよく"],
    mistakes: ["前かがみになる", "膝が上がりきらない"],
    breathing: "短く速く吐く",
    video: null,
  },
  {
    id: "mountain-climber",
    name: "マウンテンクライマー",
    nameEn: "Mountain Climber",
    parts: ["cardio", "abs"],
    equipment: ["none"],
    difficulty: 2,
    measure: "time",
    phase: "main",
    seconds: 30,
    met: 8.0,
    cues: ["肩の真下に手、体は一直線", "膝を胸に素早く引き寄せる"],
    mistakes: ["お尻が上下に跳ねる", "肩が手より前に出る"],
    breathing: "短く速く吐く",
    video: null,
  },
  {
    id: "skater",
    name: "スケーター",
    nameEn: "Skater",
    parts: ["cardio", "legs", "glutes"],
    equipment: ["none"],
    difficulty: 2,
    measure: "time",
    phase: "main",
    seconds: 30,
    met: 7.0,
    unilateral: true,
    cues: ["横に大きく跳んで片脚で着地", "着地した脚で1秒静止できる強さで"],
    mistakes: ["膝が内に入る", "上体が起きすぎてバランスを崩す"],
    breathing: "跳ぶたびに吐く",
    video: null,
  },
  {
    id: "burpee",
    name: "バーピー",
    nameEn: "Burpee",
    parts: ["cardio", "fullbody"],
    equipment: ["none"],
    difficulty: 3,
    measure: "time",
    phase: "main",
    seconds: 30,
    met: 8.0,
    cues: ["1つ1つの動作を丁寧に", "きつければジャンプを省いてOK"],
    mistakes: ["腰が反ったままプランクに入る", "フォームが崩れても回数を追う"],
    breathing: "立ち上がるときに吐く",
    video: null,
  },
  {
    id: "shadow-boxing",
    name: "シャドーボクシング",
    nameEn: "Shadow Boxing",
    parts: ["cardio", "shoulders", "abs"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "main",
    seconds: 40,
    met: 6.0,
    cues: ["軽く膝を曲げてリズムを取る", "腰の回転でパンチを出す"],
    mistakes: ["腕だけで振る", "肩に力が入りすぎる"],
    breathing: "パンチのたびに短く吐く",
    video: null,
  },

  // ───────────── クールダウン ─────────────
  {
    id: "child-pose",
    name: "チャイルドポーズ",
    nameEn: "Child's Pose",
    parts: ["back"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "cooldown",
    seconds: 40,
    met: 2.0,
    cues: ["お尻をかかとに近づけて背中を伸ばす", "手は遠くへ伸ばす"],
    mistakes: ["肩に力が入る", "呼吸が浅い"],
    breathing: "鼻から吸って口から長く吐く",
    video: null,
  },
  {
    id: "hamstring-stretch",
    name: "ハムストリングストレッチ",
    nameEn: "Hamstring Stretch",
    parts: ["legs"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "cooldown",
    seconds: 40,
    met: 2.3,
    unilateral: true,
    cues: ["背中を丸めず、股関節から折る", "痛気持ちいいところで止める"],
    mistakes: ["反動をつける", "背中を丸めて頭だけ近づける"],
    breathing: "吐きながら少しずつ深める",
    video: null,
  },
  {
    id: "chest-stretch",
    name: "胸のストレッチ",
    nameEn: "Chest Stretch",
    parts: ["chest", "shoulders"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "cooldown",
    seconds: 30,
    met: 2.3,
    cues: ["両手を背中で組んで胸を開く", "肩は下げたまま"],
    mistakes: ["腰が反る", "肩がすくむ"],
    breathing: "開くときに吐く",
    video: null,
  },
  {
    id: "quad-stretch",
    name: "太もも前のストレッチ",
    nameEn: "Quad Stretch",
    parts: ["legs"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "cooldown",
    seconds: 30,
    met: 2.3,
    unilateral: true,
    cues: ["かかとをお尻に引き寄せる", "膝を体の真横〜やや後ろに"],
    mistakes: ["腰が反る", "膝が外に開く"],
    breathing: "ゆっくり深く",
    video: null,
  },
  {
    id: "cobra-stretch",
    name: "コブラストレッチ",
    nameEn: "Cobra Stretch",
    parts: ["abs", "back"],
    equipment: ["none"],
    difficulty: 1,
    measure: "time",
    phase: "cooldown",
    seconds: 30,
    met: 2.3,
    cues: ["肘を軽く曲げたまま胸を持ち上げる", "肩を下げて首を長く"],
    mistakes: ["腰だけで反る", "肩がすくむ"],
    breathing: "反るときに吸う",
    video: null,
  },
];

export const EXERCISE_MAP: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e]),
);

export function getExercise(id: string): Exercise | undefined {
  return EXERCISE_MAP[id];
}

/** ターゲットエリア → 実際の部位 */
export const AREA_TO_PARTS: Record<TargetArea, BodyPart[]> = {
  abs: ["abs"],
  chest: ["chest"],
  armsBack: ["arms", "back", "shoulders"],
  hipsLegs: ["legs", "glutes"],
  fullbody: ["fullbody", "cardio", "abs", "chest", "arms", "back", "legs", "glutes", "shoulders"],
};

export const AREA_LABEL: Record<TargetArea, string> = {
  abs: "腹筋",
  chest: "胸部",
  armsBack: "腕と背中",
  hipsLegs: "ヒップと脚",
  fullbody: "全身",
};

export const PART_LABEL: Record<BodyPart, string> = {
  abs: "腹筋",
  chest: "胸",
  arms: "腕",
  back: "背中",
  shoulders: "肩",
  legs: "脚",
  glutes: "ヒップ",
  cardio: "カーディオ",
  fullbody: "全身",
};

export const EQUIPMENT_LABEL: Record<string, string> = {
  none: "器具なし",
  chair: "椅子",
  mat: "マット",
  dumbbell: "ダンベル",
  band: "チューブ",
};
